### PR TITLE
Properly handle empty strings

### PR DESCRIPTION
**Pull request by johanhenriksson**
Hey! I had some trouble with empty strings and strings with only symbols like ( ) etc. This is a pretty simple fix that will simply return an empty strings if there are no fragments. I also added some test cases.

Changes:
- changed convert() to return an empty string if there are no fragments.
- added test case for converting empty strings
- added test case for converting a string with only symbols
- changed revert() to return an empty string if there are no fragments.
- added test case for reverting empty strings

### CODE REVIEW

**Comment by greghuc** [comment]
I'm also having trouble calling revert('') with an empty string (which this PR doesn't cover). This broke upgrading to the new package version. 

Error: TypeError: Cannot read property 'join' of null
Line: https://github.com/stldo/url-slug/blob/master/src/index.js#L144

**Comment by johanhenriksson** [comment]
Hm, I thought I tried that 😅 

I'll add it to this PR shortly.

**Comment by greghuc** [comment]
Cool, and thanks :-)

I think `!fragments` should work for all three (revert) cases in the previous [if statement](https://github.com/stldo/url-slug/blob/master/src/index.js#L136). If `slug.match` doesn't match, it returns null, which your change handles. And if `slug.split` doesn't split, then it returns a single-element array containing `slug`.

**Comment by greghuc** [comment]
Thinking about both `convert` and `revert`, would it make more sense to return the original input, rather than an empty string? It seems strange that `instance.convert('- ( ) [ ]')` returns an empty string, and not '- ( ) [ ]'.

**Comment by johanhenriksson** [comment]
> Thinking about both `convert` and `revert`, would it make more sense to return the original input, rather than an empty string? It seems strange that `instance.convert('- ( ) [ ]')` returns an empty string, and not '- ( ) [ ]'.

Yeah, I see your point. This just happens to be the behaviour I'm going for in my particular use case, so I didn't think too much about it. But since ()[] are normally filtered out (in the case of a string of mixed symbols and alphanumeric characters), I don't think it makes sense if they remain in this case.

If you wanted to make a url slug from user input and you get the string "( )[ ]", I think its reasonable to get an empty string back, which could then be checked for e.g. minimum length before passing validation.

**Comment by stldo** [comment]
@johanhenriksson I missed that one, thank you!

**Comment by stldo** [comment]
@greghuc returning the same string could potentially return invalid characters for URLs. You can check for an empty string if you need the original value.

**Pull request merged**
